status: 200
x-ratelimit-remaining: 58
content-location: https://github.com/api/v2/json/issues/list/ask/python-github2/closed
-content-encoding: gzip
connection: keep-alive
content-length: 52973
server: nginx/1.0.4
x-runtime: 342ms
x-ratelimit-limit: 60
etag: "4a2070617d134387326d466eb9068195"
cache-control: private, max-age=0, must-revalidate
date: Thu, 25 Aug 2011 06:51:25 GMT
content-type: application/json; charset=utf-8

{"issues":[{"gravatar_id":"2b3629571060965b03e885ba93c078fc","position":1.0,"number":59,"votes":0,"created_at":"2011/07/29 19:04:58 -0700","comments":2,"body":"I want to use raw_request to complete the OAuth flow, but it doesn't respond correctly unless the Accept header is correct.","title":"Fix the Accept header.","updated_at":"2011/08/15 13:03:53 -0700","diff_url":"https://github.com/ask/python-github2/pull/59.diff","patch_url":"https://github.com/ask/python-github2/pull/59.patch","pull_request_url":"https://github.com/ask/python-github2/pull/59","closed_at":"2011/08/15 13:03:53 -0700","html_url":"https://github.com/ask/python-github2/issues/59","user":"wadey","labels":[],"state":"closed"},{"gravatar_id":"68546566350063c9017dfeae5000f6b1","position":1.0,"number":57,"votes":0,"created_at":"2011/07/12 02:48:53 -0700","comments":6,"body":"I spent a good amount of time trying to figure out the proper way to call the PullRequests.create method. I'm raising a TypeError because if the user doesn't specify a title, a NoneType error will be raised later. \r\n\r\nMaybe it would be a good idea to also write an example of the call with the format for the project name. For now I've just tried to make it more obvious which project the 'project' parameter refers to.","title":"pull-requests - raise TypeError and better docs","updated_at":"2011/07/12 09:52:23 -0700","diff_url":"https://github.com/ask/python-github2/pull/57.diff","patch_url":"https://github.com/ask/python-github2/pull/57.patch","pull_request_url":"https://github.com/ask/python-github2/pull/57","closed_at":"2011/07/12 08:32:30 -0700","html_url":"https://github.com/ask/python-github2/issues/57","user":"mapleoin","labels":[],"state":"closed"},{"gravatar_id":"2d13e27bf46a6160e0bf3d455aa7fd68","position":1.0,"number":56,"votes":0,"created_at":"2011/07/09 16:50:28 -0700","comments":5,"body":"The quickstart example in the documentation fails with \r\n\r\n>>> len(github.repos.watchers(\"ask/python-github2\"))\r\nSSLHandshakeError: [Errno 1] _ssl.c:480: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed\r\n\r\nand I cannot find any information on what to do in either the error message nor the documentation.","title":"SSL certificate verify failed","updated_at":"2011/07/10 15:34:54 -0700","diff_url":"https://github.com/ask/python-github2/pull/56.diff","patch_url":"https://github.com/ask/python-github2/pull/56.patch","pull_request_url":"https://github.com/ask/python-github2/pull/56","closed_at":"2011/07/10 15:34:23 -0700","html_url":"https://github.com/ask/python-github2/issues/56","user":"ukoethe","labels":[],"state":"closed"},{"gravatar_id":"9124210529f6eb59754932c413dd3c69","position":1.0,"number":54,"votes":0,"created_at":"2011/06/29 16:05:17 -0700","comments":1,"body":"","title":"added possibility to list all repositories of certain organization","updated_at":"2011/06/30 09:43:40 -0700","diff_url":"https://github.com/ask/python-github2/pull/54.diff","patch_url":"https://github.com/ask/python-github2/pull/54.patch","pull_request_url":"https://github.com/ask/python-github2/pull/54","closed_at":"2011/06/30 09:43:40 -0700","html_url":"https://github.com/ask/python-github2/issues/54","user":"garbas","labels":[],"state":"closed"},{"gravatar_id":"e40de1eb6e8a74cb96b3f07f3994f155","position":53.0,"number":53,"votes":0,"created_at":"2011/05/28 22:15:49 -0700","comments":2,"body":"It would make more sense, and be easy to filter wanted data, if debug info was handled with the `logging` module.  Side effect being the output will change significantly, but does it matter for debugging output anyway?","title":"Use logging for debug information.","updated_at":"2011/06/20 09:43:44 -0700","closed_at":"2011/06/20 09:43:44 -0700","html_url":"https://github.com/ask/python-github2/issues/53","user":"JNRowe","labels":[],"state":"closed"},{"gravatar_id":"e40de1eb6e8a74cb96b3f07f3994f155","position":52.0,"number":52,"votes":0,"created_at":"2011/05/28 02:03:37 -0700","comments":0,"body":"\nSee [this bug](https://github.com/ask/python-github2/issues/51#issuecomment-1253464)","title":"Document purpose, and use, of ``debug`` attributes.","updated_at":"2011/05/28 06:40:00 -0700","closed_at":"2011/05/28 06:40:00 -0700","html_url":"https://github.com/ask/python-github2/issues/52","user":"JNRowe","labels":[],"state":"closed"},{"gravatar_id":"fab591eb34c76cbd0716024ce22d4906","position":51.0,"number":51,"votes":0,"created_at":"2011/05/28 01:09:46 -0700","comments":14,"body":"```pycon \r\n>>> github.repos.watch(\"schacon/grit\")\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/repositories.py\", line 69, in watch\r\n    return self.make_request(\"watch\", project)\r\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/core.py\", line 58, in make_request\r\n    response = self.request.get(self.domain, command, *args)\r\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/request.py\", line 70, in get\r\n    return self.make_request(\"/\".join(path_components))\r\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/request.py\", line 89, in make_request\r\n    result = self.raw_request(url, extra_post_data, method=method)\r\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/request.py\", line 113, in raw_request\r\n    response.status, content))\r\nRuntimeError: unexpected response from github.com 401: '{\"error\":\"invalid repository to watch\"}'\r\n\r\n```\r\n\r\nI can't seem to watch that repository.  I used the OAuth key to get the github object. ","title":"Watching repositories doesn't work","updated_at":"2011/06/02 07:57:47 -0700","closed_at":"2011/05/28 20:30:11 -0700","html_url":"https://github.com/ask/python-github2/issues/51","user":"myusuf3","labels":[],"state":"closed"},{"gravatar_id":"2f3f68f62f5fc642f0b716b355071176","position":50.0,"number":50,"votes":0,"created_at":"2011/05/23 18:05:57 -0700","comments":2,"body":"","title":"Fixing the init of the proxy code.","updated_at":"2011/05/23 21:09:45 -0700","diff_url":"https://github.com/ask/python-github2/pull/50.diff","patch_url":"https://github.com/ask/python-github2/pull/50.patch","pull_request_url":"https://github.com/ask/python-github2/pull/50","closed_at":"2011/05/23 20:43:20 -0700","html_url":"https://github.com/ask/python-github2/issues/50","user":"hub-cap","labels":[],"state":"closed"},{"gravatar_id":"fab591eb34c76cbd0716024ce22d4906","position":49.0,"number":49,"votes":0,"created_at":"2011/05/20 11:46:19 -0700","comments":8,"body":"I am was wondering if you could better document the Mocks being used for testing. I wouldn't mind writing up the test cases, if you could comment the testing code that is currently present. Increase the robustness of the project. \n\nThoughts? Even a link to the background knowledge needed to understand what you are doing. I am tried creating a couple of tests in my branch but unable to get anything but errors. \n\nMaybe a wiki describing setup and what needs to be done. ","title":"Testing Documentation/Wiki","updated_at":"2011/05/22 14:25:06 -0700","closed_at":"2011/05/22 14:25:06 -0700","html_url":"https://github.com/ask/python-github2/issues/49","user":"myusuf3","labels":[],"state":"closed"},{"gravatar_id":"2f3f68f62f5fc642f0b716b355071176","position":48.0,"number":48,"votes":0,"created_at":"2011/05/19 08:40:47 -0700","comments":3,"body":"* Added basic proxy support documentation","title":"Add proxy documentation","updated_at":"2011/05/19 15:12:47 -0700","diff_url":"https://github.com/ask/python-github2/pull/48.diff","patch_url":"https://github.com/ask/python-github2/pull/48.patch","pull_request_url":"https://github.com/ask/python-github2/pull/48","closed_at":"2011/05/19 15:09:09 -0700","html_url":"https://github.com/ask/python-github2/issues/48","user":"hub-cap","labels":[],"state":"closed"},{"gravatar_id":"2f3f68f62f5fc642f0b716b355071176","position":47.0,"number":47,"votes":0,"created_at":"2011/05/18 18:40:20 -0700","comments":1,"body":"Made the socks stuff optional. I wasnt able to test the extras_require portion of the setup.py (im not terribly well versed in setuptools) but i tested manually by uninstalling/reinstalling the socks lib and watching the error raised.","title":"Updated Add Proxy Support - now optional","updated_at":"2011/05/18 19:04:30 -0700","diff_url":"https://github.com/ask/python-github2/pull/47.diff","patch_url":"https://github.com/ask/python-github2/pull/47.patch","pull_request_url":"https://github.com/ask/python-github2/pull/47","closed_at":"2011/05/18 19:04:29 -0700","html_url":"https://github.com/ask/python-github2/issues/47","user":"hub-cap","labels":[],"state":"closed"},{"gravatar_id":"2f3f68f62f5fc642f0b716b355071176","position":46.0,"number":46,"votes":0,"created_at":"2011/05/18 09:37:00 -0700","comments":12,"body":"Adding HTTP proxy settings to the client, as well as to the request to allow github2 to be used behind a HTTP proxy","title":"Adding HTTP Proxy support to the Request and Client","updated_at":"2011/05/23 18:06:30 -0700","diff_url":"https://github.com/ask/python-github2/pull/46.diff","patch_url":"https://github.com/ask/python-github2/pull/46.patch","pull_request_url":"https://github.com/ask/python-github2/pull/46","closed_at":"2011/05/19 07:59:05 -0700","html_url":"https://github.com/ask/python-github2/issues/46","user":"hub-cap","labels":[],"state":"closed"},{"gravatar_id":"2f3f68f62f5fc642f0b716b355071176","position":45.0,"number":45,"votes":0,"created_at":"2011/05/18 08:47:38 -0700","comments":1,"body":"Adding HTTP proxy settings to the client, as well as to the request to allow github2 to be used behind a HTTP proxy","title":"Adding HTTP Proxy support to the Request and Client","updated_at":"2011/05/18 09:07:34 -0700","diff_url":"https://github.com/ask/python-github2/pull/45.diff","patch_url":"https://github.com/ask/python-github2/pull/45.patch","pull_request_url":"https://github.com/ask/python-github2/pull/45","closed_at":"2011/05/18 09:07:33 -0700","html_url":"https://github.com/ask/python-github2/issues/45","user":"hub-cap","labels":[],"state":"closed"},{"gravatar_id":"fab591eb34c76cbd0716024ce22d4906","position":44.0,"number":44,"votes":0,"created_at":"2011/05/14 20:43:34 -0700","comments":13,"body":"When getting the commits for repositories that have '.' it can't seem to find the repository.\n\n``` pycon\n>>> commits += github.commits.list('kennethreitz/osxpython.org')\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/commits.py\", line 37, in list\n    filter=\"commits\", datatype=Commit)\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/core.py\", line 75, in get_values\n    values = self.make_request(*args, **kwargs)\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/core.py\", line 58, in make_request\n    response = self.request.get(self.domain, command, *args)\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/request.py\", line 70, in get\n    return self.make_request(\"/\".join(path_components))\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/request.py\", line 89, in make_request\n    result = self.raw_request(url, extra_post_data, method=method)\n  File \"/srv/python-environments/prologger/lib/python2.6/site-packages/github2/request.py\", line 113, in raw_request\n    response.status, content))\nRuntimeError: unexpected response from github.com 404: '{\"error\":\"Not Found\"}'\n```","title":"repositories with '.' are not found","updated_at":"2011/05/26 23:46:28 -0700","closed_at":"2011/05/26 18:03:57 -0700","html_url":"https://github.com/ask/python-github2/issues/44","user":"myusuf3","labels":[],"state":"closed"},{"gravatar_id":"2028496e3344d92d8b3af64eb0d9e19e","position":43.0,"number":43,"votes":0,"created_at":"2011/05/09 20:51:03 -0700","comments":8,"body":"The docs are already using Sphinx. It'd be much more convenient if they were hosted.\r\n\r\nhttp://Readthedocs.org is free and sphinx powered, getting them up there should be easy.\r\n\r\nFun even.","title":"Read the Docs","updated_at":"2011/05/11 07:02:48 -0700","closed_at":"2011/05/11 06:44:44 -0700","html_url":"https://github.com/ask/python-github2/issues/43","user":"GraylinKim","labels":[],"state":"closed"},{"gravatar_id":"b7699be15e710c4be309f9d537fb252b","position":42.0,"number":42,"votes":0,"created_at":"2011/05/09 08:24:36 -0700","comments":12,"body":"This is my just running 2to3 over the library, and fixing one or two things with json. Don't know if you want or need it. I'm using it for some blogofile stuff, which just bumped to python 3 for all main development, and wanted to keep using your work with my site.","title":"Python3","updated_at":"2011/05/23 00:55:08 -0700","diff_url":"https://github.com/ask/python-github2/pull/42.diff","patch_url":"https://github.com/ask/python-github2/pull/42.patch","pull_request_url":"https://github.com/ask/python-github2/pull/42","closed_at":"2011/05/19 15:19:30 -0700","html_url":"https://github.com/ask/python-github2/issues/42","user":"goosemo","labels":[],"state":"closed"},{"gravatar_id":"fab591eb34c76cbd0716024ce22d4906","position":41.0,"number":41,"votes":0,"created_at":"2011/04/24 09:35:15 -0700","comments":3,"body":"","title":"Easy way to call tests from cli","updated_at":"2011/04/27 09:45:11 -0700","diff_url":"https://github.com/ask/python-github2/pull/41.diff","patch_url":"https://github.com/ask/python-github2/pull/41.patch","pull_request_url":"https://github.com/ask/python-github2/pull/41","closed_at":"2011/04/27 09:45:11 -0700","html_url":"https://github.com/ask/python-github2/issues/41","user":"myusuf3","labels":[],"state":"closed"},{"gravatar_id":"464f76c5577389c5ca29e3d7cca133d5","position":40.0,"number":40,"votes":0,"created_at":"2011/04/22 12:26:50 -0700","comments":3,"body":"https://github.com/broderboy/python-github2/commit/48d85d517b4e51652217b71b264c866caa5ca874\r\n\r\nI'm not sure why git put that as a full file change\r\nline changed: prune doc/.build\r\n\r\nThanks\r\n\r\nOriginal Error: \r\nrunning install\r\nrunning bdist_egg\r\nrunning egg_info\r\nwriting requirements to github2.egg-info\\requires.txt\r\nwriting github2.egg-info\\PKG-INFO\r\nwriting top-level names to github2.egg-info\\top_level.txt\r\nwriting dependency_links to github2.egg-info\\dependency_links.txt\r\nwriting requirements to github2.egg-info\\requires.txt\r\nwriting github2.egg-info\\PKG-INFO\r\nwriting top-level names to github2.egg-info\\top_level.txt\r\nwriting dependency_links to github2.egg-info\\dependency_links.txt\r\nreading manifest file 'github2.egg-info\\SOURCES.txt'\r\nreading manifest template 'MANIFEST.in'\r\nTraceback (most recent call last):\r\n  File \".\\setup.py\", line 46, in <module>\r\n    \"Topic :: Software Development :: Libraries\",\r\n  File \"C:\\Python26\\lib\\distutils\\core.py\", line 152, in setup\r\n    dist.run_commands()\r\n  File \"C:\\Python26\\lib\\distutils\\dist.py\", line 975, in run_commands\r\n    self.run_command(cmd)\r\n  File \"C:\\Python26\\lib\\distutils\\dist.py\", line 995, in run_command\r\n    cmd_obj.run()\r\n  File \"C:\\Python26\\lib\\site-packages\\distribute-0.6.10-py2.6.egg\\setuptools\\command\\install.py\", line 73, in run\r\n    self.do_egg_install()\r\n  File \"C:\\Python26\\lib\\site-packages\\distribute-0.6.10-py2.6.egg\\setuptools\\command\\install.py\", line 93, in do_egg_install\r\n    self.run_command('bdist_egg')\r\n  File \"C:\\Python26\\lib\\distutils\\cmd.py\", line 333, in run_command\r\n    self.distribution.run_command(command)\r\n  File \"C:\\Python26\\lib\\distutils\\dist.py\", line 995, in run_command\r\n    cmd_obj.run()\r\n  File \"C:\\Python26\\lib\\site-packages\\distribute-0.6.10-py2.6.egg\\setuptools\\command\\bdist_egg.py\", line 167, in run\r\n    self.run_command(\"egg_info\")\r\n  File \"C:\\Python26\\lib\\distutils\\cmd.py\", line 333, in run_command\r\n    self.distribution.run_command(command)\r\n  File \"C:\\Python26\\lib\\distutils\\dist.py\", line 995, in run_command\r\n    cmd_obj.run()\r\n  File \"C:\\Python26\\lib\\site-packages\\distribute-0.6.10-py2.6.egg\\setuptools\\command\\egg_info.py\", line 179, in run\r\n    self.find_sources()\r\n  File \"C:\\Python26\\lib\\site-packages\\distribute-0.6.10-py2.6.egg\\setuptools\\command\\egg_info.py\", line 254, in find_sources\r\n    mm.run()\r\n  File \"C:\\Python26\\lib\\site-packages\\distribute-0.6.10-py2.6.egg\\setuptools\\command\\egg_info.py\", line 310, in run\r\n    self.read_template()\r\n  File \"C:\\Python26\\lib\\site-packages\\distribute-0.6.10-py2.6.egg\\setuptools\\command\\sdist.py\", line 204, in read_template\r\n    _sdist.read_template(self)\r\n  File \"C:\\Python26\\lib\\distutils\\command\\sdist.py\", line 336, in read_template\r\n    self.filelist.process_template_line(line)\r\n  File \"C:\\Python26\\lib\\distutils\\filelist.py\", line 129, in process_template_line\r\n    (action, patterns, dir, dir_pattern) = self._parse_template_line(line)\r\n  File \"C:\\Python26\\lib\\distutils\\filelist.py\", line 112, in _parse_template_line\r\n    dir_pattern = convert_path(words[1])\r\n  File \"C:\\Python26\\lib\\distutils\\util.py\", line 201, in convert_path\r\n    raise ValueError, \"path '%s' cannot end with '/'\" % pathname\r\nValueError: path 'doc/.build/' cannot end with '/'","title":"Modified MANIFEST.in. It wasn't installing on Windows","updated_at":"2011/04/23 07:18:49 -0700","diff_url":"https://github.com/ask/python-github2/pull/40.diff","patch_url":"https://github.com/ask/python-github2/pull/40.patch","pull_request_url":"https://github.com/ask/python-github2/pull/40","closed_at":"2011/04/23 04:53:48 -0700","html_url":"https://github.com/ask/python-github2/issues/40","user":"broderboy","labels":[],"state":"closed"},{"gravatar_id":"e40de1eb6e8a74cb96b3f07f3994f155","position":39.0,"number":39,"votes":0,"created_at":"2011/04/18 08:25:47 -0700","comments":4,"body":"\nFeeble brainstorming session...\n\nI've just been bitten quite badly by the lack of timezone handling, the cause is the use of naive datetime objects in the 'GitHub' timezone(`America/Los_Angeles`).  While processing some tasks that span the PST/PDT changeover the ordering of events is broken.\n\nOptions are:\n\n1. Leave alone and try to process the datetime objects externally, somewhat easy but not a good solution as it requires duplication in each project that requires accurate date handling\n2. Start producing non-naive datetime objects, breaks any caller who is not prepared for it.\n3. Introduce a setting to toggle naive object availability, defaulting to naive objects to maintain backwards compatibility\n\n[python-dateutil](http://labix.org/python-dateutil) makes handling option 1 quite easy, and also simplifies the handling of option 3 at the cost of another external dependency.  Option 2 is just pure evil, or pure stupidity depending on point of view.\n\nOption 3 results in a parsing using something like the following entirely untested code:\n\n    datetime_ = parser.parse(github_date)\n    if NAIVE:\n        datetime_.replace(tzinfo=None)\n    return datetime_\n\nAnd similarly producing GitHub compatible date strings would require handling of naive formats with equally untested code such as:\n\n    if NAIVE:\n        datetime_ = datetime_.replace(tz.gettz(\"America/Los_Angeles\"))\n    return datetime_.strftime(\"%Y/%m/%d %H:%M:%S %z\")","title":"Datetime timezone handling.","updated_at":"2011/06/23 02:33:57 -0700","diff_url":"https://github.com/ask/python-github2/pull/39.diff","patch_url":"https://github.com/ask/python-github2/pull/39.patch","pull_request_url":"https://github.com/ask/python-github2/pull/39","closed_at":"2011/06/23 02:33:57 -0700","html_url":"https://github.com/ask/python-github2/issues/39","user":"JNRowe","labels":[],"state":"closed"},{"gravatar_id":"fab591eb34c76cbd0716024ce22d4906","position":38.0,"number":38,"votes":0,"created_at":"2011/04/17 17:11:51 -0700","comments":9,"body":"e.g when I am using the call \r\n\r\nGithub(access_token=oauthtoken) -- it seems to work fine for all calls expect, the following call \r\n\r\nproject being repo.project\r\n\r\ncommits += self.client.commits.list(str(project))\r\n\r\n\r\nI get the follow exception\r\n\r\nunexpected response from github.com 401: '{\"error\":\"Couldn\\'t authenticate you\"}'\r\n\r\nI managed to work around this issue by creating the self.client using the following instantiation \r\n\r\nGithub(self.oauthtoken)\r\n\r\nIt probably not being pass down the OAuth token on the particular call. \r\n","title":"OAuth token isn't being passed down","updated_at":"2011/05/11 09:48:20 -0700","closed_at":"2011/05/11 09:48:20 -0700","html_url":"https://github.com/ask/python-github2/issues/38","user":"myusuf3","labels":[],"state":"closed"},{"gravatar_id":"2c8089a78bf15883302e9ac5b4367895","position":37.0,"number":37,"votes":0,"created_at":"2011/04/14 17:19:33 -0700","comments":2,"body":"The current [Commits API](http://develop.github.com/p/commits.html) specifies a user_id in the pathspec:\n\n`commits/list/:user_id/:repository/:branch`\n`commits/list/:user_id/:repository/:branch/*path`\n\nThis parameter was not present in the `list` or `show`  methods of the `Commits` class, consequently requesting commits was not possible (as far as I could tell)\n\n","title":"added user_id to commits path spec","updated_at":"2011/04/15 05:13:56 -0700","diff_url":"https://github.com/ask/python-github2/pull/37.diff","patch_url":"https://github.com/ask/python-github2/pull/37.patch","pull_request_url":"https://github.com/ask/python-github2/pull/37","closed_at":"2011/04/15 05:13:56 -0700","html_url":"https://github.com/ask/python-github2/issues/37","user":"loganlinn","labels":[],"state":"closed"},{"gravatar_id":"e40de1eb6e8a74cb96b3f07f3994f155","position":36.0,"number":36,"votes":0,"created_at":"2011/04/12 03:47:52 -0700","comments":2,"body":"@ask and interested others,\r\n\r\nYou said to treat the repo like home, but I just wanted to run this past you in case you have objections.\r\n\r\nThe changes are quite invasive.  It strips out the examples from `README.rst`(it is a bit cluttered IMO), reformats many docstrings for use with Sphinx's [autodoc](http://sphinx.pocoo.org/tutorial.html#autodoc), fiddles with the cool `Attribute` docstring generator, etc.\r\n\r\nOpinions?  If part of it is okay, say which part and I'll remove/rework the rest.  If you hate it all just say so, it won't hurt my feelings I promise ;)\r\n\r\nThanks,\r\n\r\nJames","title":"Using Sphinx doc for documentation","updated_at":"2011/04/13 13:06:16 -0700","diff_url":"https://github.com/ask/python-github2/pull/36.diff","patch_url":"https://github.com/ask/python-github2/pull/36.patch","pull_request_url":"https://github.com/ask/python-github2/pull/36","closed_at":"2011/04/13 13:01:44 -0700","html_url":"https://github.com/ask/python-github2/issues/36","user":"JNRowe","labels":[],"state":"closed"},{"gravatar_id":"1ee6b40a1acbcc00eb32e306e0e94037","position":35.0,"number":35,"votes":0,"created_at":"2011/04/10 18:02:50 -0700","comments":1,"body":"I added a function to get all blobs as a dictionary between the path & sha for a given tree. ","title":"Get All Blobs","updated_at":"2011/04/11 02:38:53 -0700","diff_url":"https://github.com/ask/python-github2/pull/35.diff","patch_url":"https://github.com/ask/python-github2/pull/35.patch","pull_request_url":"https://github.com/ask/python-github2/pull/35","closed_at":"2011/04/11 02:38:53 -0700","html_url":"https://github.com/ask/python-github2/issues/35","user":"surajram","labels":[],"state":"closed"},{"gravatar_id":"3aa27c0add742f542848af3b8a9e980c","position":34.0,"number":34,"votes":0,"created_at":"2011/03/26 10:57:22 -0700","comments":4,"body":"e.g. github.repos.list() specifies following behaviour: \"If no user is given, repositoris for the currently logged in user are returned.\"\r\n\r\nHowever this works only if using username for authentication but with OAuth2 access token following error is thrown:\r\n\r\nRuntimeError: unexpected response from github.com 401: '{\"error\":\"api route not recognized\"}'\r\n\r\nWorkaround for this is to request current username using following pattern:\r\n\r\nuser = github.users.show(\"\")\r\n\r\nand then use returned username as an parameter for list(). \r\n\r\nI guess we need to populate the internal username in a constructor via show API when username is not given or is there better solution?\r\n\r\n\r\n\r\n\r\n\r\n","title":"Getting \"currently logged in user data\" when using access_token","updated_at":"2011/05/10 06:57:46 -0700","diff_url":"https://github.com/ask/python-github2/pull/34.diff","patch_url":"https://github.com/ask/python-github2/pull/34.patch","pull_request_url":"https://github.com/ask/python-github2/pull/34","closed_at":"2011/05/10 06:57:46 -0700","html_url":"https://github.com/ask/python-github2/issues/34","user":"pmuilu","labels":[],"state":"closed"},{"gravatar_id":"e40de1eb6e8a74cb96b3f07f3994f155","position":33.0,"number":33,"votes":0,"created_at":"2011/03/03 09:26:59 -0800","comments":7,"body":"A few months ago when playing with `python-github2` I switched to using `httplib2` for network requests.  I hadn't really planned on opening a pull request, but I've been using it as my full time branch so I've changed my mind :).\r\n\r\nThe benefits of `httplib2` are the (imo) simplification of the request handling, built-in caching support with effortless `ETag` handling and free HTTP compression support should GitHub enable it at some point..\r\n\r\nI'm just curious how you guys feel about it.  Maybe there are some changes to be made to make it pullable, maybe you just don't like the idea of another external dependency or <insert other ideas>.\r\n\r\nThanks,\r\n\r\nJames","title":"RFC: httplib2 usage","updated_at":"2011/04/11 02:41:30 -0700","diff_url":"https://github.com/ask/python-github2/pull/33.diff","patch_url":"https://github.com/ask/python-github2/pull/33.patch","pull_request_url":"https://github.com/ask/python-github2/pull/33","closed_at":"2011/04/11 02:41:30 -0700","html_url":"https://github.com/ask/python-github2/issues/33","user":"JNRowe","labels":[],"state":"closed"},{"gravatar_id":"1dc7387cedba30b9a3d12792084b4b4a","position":32.0,"number":32,"votes":0,"created_at":"2011/02/19 07:18:36 -0800","comments":1,"body":"Added two operations in the issues module: list labels and search issues by label.","title":"List labels and Search Issues by Label","updated_at":"2011/04/09 10:25:23 -0700","diff_url":"https://github.com/ask/python-github2/pull/32.diff","patch_url":"https://github.com/ask/python-github2/pull/32.patch","pull_request_url":"https://github.com/ask/python-github2/pull/32","closed_at":"2011/04/09 10:25:23 -0700","html_url":"https://github.com/ask/python-github2/issues/32","user":"bartdag","labels":[],"state":"closed"},{"gravatar_id":"e40de1eb6e8a74cb96b3f07f3994f155","position":31.0,"number":31,"votes":0,"created_at":"2011/02/16 06:44:12 -0800","comments":1,"body":"Adding or removing labels has recently broken, this small change to force `POST` fixes it.\r\n\r\nThanks,\r\n\r\nJames","title":"Fix issue label addition/removal.","updated_at":"2011/04/09 10:36:11 -0700","diff_url":"https://github.com/ask/python-github2/pull/31.diff","patch_url":"https://github.com/ask/python-github2/pull/31.patch","pull_request_url":"https://github.com/ask/python-github2/pull/31","closed_at":"2011/04/09 10:36:11 -0700","html_url":"https://github.com/ask/python-github2/issues/31","user":"JNRowe","labels":[],"state":"closed"},{"gravatar_id":"377e59815b7b7d6dfc23c808f0d07f05","position":30.0,"number":30,"votes":1,"created_at":"2011/02/15 12:30:09 -0800","comments":1,"body":"From:\r\n\r\nhttp://develop.github.com/p/repo.html\r\n\r\nrepos.delete returns a dictionary with a delete_token key.  This key then needs to be POST'd back to the same URL.  The repos.delete method as it is does nothing with this key and does not accept a post_data dictionary as a keyword argument.","title":"repos.delete not functional","updated_at":"2011/04/13 13:01:43 -0700","closed_at":"2011/04/13 13:01:43 -0700","html_url":"https://github.com/ask/python-github2/issues/30","user":"sxalexander","labels":[],"state":"closed"},{"gravatar_id":"d7ed4dc5ad80ffecb3aed70fc7190e52","position":29.0,"number":29,"votes":0,"created_at":"2011/01/25 07:13:12 -0800","comments":1,"body":"Steps to reproduce:\n\nfrom github2.client import Github\nclient = Github(username='<your username>', api_token='<your token>', requests_per_second=1)\npull_req = client.request.get('pulls', 'username/repo_name', '<pull request number>')\n\nThis works fine for most pull requests. However, if a commit associated with the pull request has 'line notes', it seems to fail.\nAs an example, you can try this on one of my pull requests:\n\npull_req = client.request.get('pulls', 'larsbutler/roundabout', '1')","title":"\"Github Server Error\" when trying to get pull requests which include line notes","updated_at":"2011/01/25 08:16:09 -0800","closed_at":"2011/01/25 08:16:09 -0800","html_url":"https://github.com/ask/python-github2/issues/29","user":"larsbutler","labels":[],"state":"closed"},{"gravatar_id":"4174216c1dc0f223ce608d5a3b66a585","position":28.0,"number":28,"votes":0,"created_at":"2010/12/30 10:28:59 -0800","comments":8,"body":"This implements the github API pull requests functionality. ","title":"Pull requests","updated_at":"2011/05/29 08:27:58 -0700","diff_url":"https://github.com/ask/python-github2/pull/28.diff","patch_url":"https://github.com/ask/python-github2/pull/28.patch","pull_request_url":"https://github.com/ask/python-github2/pull/28","closed_at":"2011/05/29 08:27:23 -0700","html_url":"https://github.com/ask/python-github2/issues/28","user":"ChristopherMacGown","labels":[],"state":"closed"},{"gravatar_id":"cf04727870245c17f455fb05b25f9f8e","position":27.0,"number":27,"votes":0,"created_at":"2010/12/21 12:37:06 -0800","comments":0,"body":"The URL wasn't escaped properly when labels included a space \"This is a label\" during the add_label request.","title":"Failed to add a label with a space to an issue ","updated_at":"2011/04/09 09:47:50 -0700","diff_url":"https://github.com/ask/python-github2/pull/27.diff","patch_url":"https://github.com/ask/python-github2/pull/27.patch","pull_request_url":"https://github.com/ask/python-github2/pull/27","closed_at":"2011/04/09 09:47:50 -0700","html_url":"https://github.com/ask/python-github2/issues/27","user":"jweinberg","labels":[],"state":"closed"},{"gravatar_id":"4174216c1dc0f223ce608d5a3b66a585","position":26.0,"number":26,"votes":0,"created_at":"2010/12/16 13:59:45 -0800","comments":1,"body":"","title":"Patch to add organizations and teams.","updated_at":"2010/12/30 10:30:53 -0800","diff_url":"https://github.com/ask/python-github2/pull/26.diff","patch_url":"https://github.com/ask/python-github2/pull/26.patch","pull_request_url":"https://github.com/ask/python-github2/pull/26","closed_at":"2010/12/30 10:30:53 -0800","html_url":"https://github.com/ask/python-github2/issues/26","user":"ChristopherMacGown","labels":[],"state":"closed"},{"gravatar_id":"e40de1eb6e8a74cb96b3f07f3994f155","position":25.0,"number":25,"votes":0,"created_at":"2010/12/10 23:18:57 -0800","comments":1,"body":"As [nvie](http://github.com/nvie) rightly pointed out in [my other pull request](https://github.com/ask/python-github2/pull/14#issuecomment-601878), I hadn't added any documentation for my changes... here that is.\r\n\r\nI've also fixed issue searches for multiple words. I only spotted the problem as a result of adding the entry to `README.rst`, so I should probably learn something from that ;)\r\n\r\nFinally, there is some slight reformatting of the documentation.  *Most* of the text was wrapped at ~80 characters and code samples indented 4 spaces, the [final commit](https://github.com/JNRowe/python-github2/commit/ff9132f9054bcc3827c94fd927c30cf257d84954) just makes that consistent across the rest of the documentation.  I realise that may be controversial, but wrapped or not wrapped it should at least be consistent.\r\n\r\nThanks,\r\n\r\nJames","title":"Fix for issue searching and documentation updates.","updated_at":"2010/12/12 23:27:36 -0800","diff_url":"https://github.com/ask/python-github2/pull/25.diff","patch_url":"https://github.com/ask/python-github2/pull/25.patch","pull_request_url":"https://github.com/ask/python-github2/pull/25","closed_at":"2010/12/12 23:27:36 -0800","html_url":"https://github.com/ask/python-github2/issues/25","user":"JNRowe","labels":[],"state":"closed"},{"gravatar_id":"c5a7f21b46df698f3db31c37ed0cf55a","position":23.0,"number":23,"votes":0,"created_at":"2010/12/08 00:17:49 -0800","comments":4,"body":"See the docs at http://develop.github.com/p/orgs.html","title":"Add support for the new Organizations API","updated_at":"2011/05/10 06:53:12 -0700","closed_at":"2011/05/10 06:12:12 -0700","html_url":"https://github.com/ask/python-github2/issues/23","user":"nvie","labels":[],"state":"closed"},{"gravatar_id":"c5a7f21b46df698f3db31c37ed0cf55a","position":22.0,"number":22,"votes":0,"created_at":"2010/12/06 21:28:03 -0800","comments":0,"body":"Hi Ask,\r\n\r\nI added support for authenticating using Github's OAuth service. When you do this, you get an access_token, which you can now use instead of the username/api_token combination. You pass it in to the Github constructor like this:\r\n\r\n    github = Github(access_token=\"...\")\r\n\r\nIt puts the access_token on the GET request, like described in the third bullet under [Web Application Flow](https://gist.github.com/419219).\r\n\r\nIts use is documented in the README file.\r\n\r\nCheers,\r\nVincent\r\n","title":"Added support for Github's OAuth-based URL requests","updated_at":"2010/12/08 00:16:25 -0800","diff_url":"https://github.com/ask/python-github2/pull/22.diff","patch_url":"https://github.com/ask/python-github2/pull/22.patch","pull_request_url":"https://github.com/ask/python-github2/pull/22","closed_at":"2010/12/08 00:16:25 -0800","html_url":"https://github.com/ask/python-github2/issues/22","user":"nvie","labels":[],"state":"closed"},{"gravatar_id":"c5a7f21b46df698f3db31c37ed0cf55a","position":21.0,"number":21,"votes":0,"created_at":"2010/12/06 13:10:09 -0800","comments":1,"body":"Hi Ask,\r\n\r\nToday, I commited several patches. First of all, I added support for authenticating using `Github(access_token=\"...\")` GET requests instead of `Github(username=\"foo\", api_token=\"...\")` POST requests.  This is the way Github API v2 URLs need to be called when using their (experimental) OAuth model.\r\n\r\nFurthermore, while I was testing this, the Github API seems to have changed the format of all dates to be nice UTC dates with timezone info. This makes the special conversion hoops and tricks unnecessary, so I removed them.  For safety, I kept the \"flexible date conversion function lookup\" construct around, but maybe this could be removed as a whole. I'll leave this judgement up to you.\r\n\r\nHave a blast!\r\n\r\nCheers,\r\nVincent\r\n","title":"Add support for OAuth URLs, and a fix for date format","updated_at":"2010/12/06 21:28:42 -0800","diff_url":"https://github.com/ask/python-github2/pull/21.diff","patch_url":"https://github.com/ask/python-github2/pull/21.patch","pull_request_url":"https://github.com/ask/python-github2/pull/21","closed_at":"2010/12/06 21:28:42 -0800","html_url":"https://github.com/ask/python-github2/issues/21","user":"nvie","labels":[],"state":"closed"},{"gravatar_id":"9de3f3969367fffe2051c2b405b79810","position":20.0,"number":20,"votes":0,"created_at":"2010/11/25 16:07:26 -0800","comments":1,"body":"http://develop.github.com/p/repo.html:\r\n\r\n\"To get a list of repos you can push to that are not your own, GET\r\n\r\nrepos/pushable\"\r\n\r\nI was surprised not to find this, so I added it.","title":"Added github.repos.pushable() as described in the API documentation.","updated_at":"2010/11/26 13:37:12 -0800","diff_url":"https://github.com/ask/python-github2/pull/20.diff","patch_url":"https://github.com/ask/python-github2/pull/20.patch","pull_request_url":"https://github.com/ask/python-github2/pull/20","closed_at":"2010/11/26 13:37:12 -0800","html_url":"https://github.com/ask/python-github2/issues/20","user":"johl","labels":[],"state":"closed"},{"gravatar_id":"f3794e603ef53b0513ab45b6565ee457","position":19.0,"number":19,"votes":0,"created_at":"2010/11/19 21:23:56 -0800","comments":5,"body":"I realized I didn't include fractions of a second in my earlier api-limits change.  This one does. \r\n\r\nThis pull includes my commits from repo-project as well.","title":"Api limits","updated_at":"2010/11/26 13:25:25 -0800","diff_url":"https://github.com/ask/python-github2/pull/19.diff","patch_url":"https://github.com/ask/python-github2/pull/19.patch","pull_request_url":"https://github.com/ask/python-github2/pull/19","closed_at":"2010/11/26 13:25:25 -0800","html_url":"https://github.com/ask/python-github2/issues/19","user":"jdunck","labels":[],"state":"closed"},{"gravatar_id":"f3794e603ef53b0513ab45b6565ee457","position":18.0,"number":18,"votes":0,"created_at":"2010/11/19 21:00:10 -0800","comments":0,"body":"Hey Ask, I added a Repo.project property - in my client code, I'm fairly often having to pass the project string to methods, and writing owner+'/'+name is getting boring.  :-)","title":"Repo project","updated_at":"2010/11/20 12:08:27 -0800","diff_url":"https://github.com/ask/python-github2/pull/18.diff","patch_url":"https://github.com/ask/python-github2/pull/18.patch","pull_request_url":"https://github.com/ask/python-github2/pull/18","closed_at":"2010/11/20 12:08:27 -0800","html_url":"https://github.com/ask/python-github2/issues/18","user":"jdunck","labels":[],"state":"closed"},{"gravatar_id":"ad448ae5b261e252ddaeeccf5c69a4ba","position":17.0,"number":17,"votes":1,"created_at":"2010/11/12 04:14:24 -0800","comments":1,"body":"This is very useful and provided by the underlying api and I would like to use it for my cmd line tool - https://github.com/kashifrazzaqui/github-issues\r\n\r\nIf you will please add this.\r\nThanks.","title":"List does not allow filteration by label","updated_at":"2011/04/09 10:51:59 -0700","closed_at":"2011/04/09 10:51:59 -0700","html_url":"https://github.com/ask/python-github2/issues/17","user":"kashifrazzaqui","labels":[],"state":"closed"},{"gravatar_id":"67e05420d4dd3492097aeb77f44f7867","position":16.0,"number":16,"votes":0,"created_at":"2010/11/04 17:26:33 -0700","comments":0,"body":"Fixes https://github.com/ask/python-github2/issues#issue/15\r\n\r\nThis was caused by github switching to HTTPS. Is in production at http://djangopackages.com","title":"Changed over to HTTPS","updated_at":"2010/11/24 06:10:48 -0800","diff_url":"https://github.com/ask/python-github2/pull/16.diff","patch_url":"https://github.com/ask/python-github2/pull/16.patch","pull_request_url":"https://github.com/ask/python-github2/pull/16","closed_at":"2010/11/24 06:10:48 -0800","html_url":"https://github.com/ask/python-github2/issues/16","user":"pydanny","labels":[],"state":"closed"},{"gravatar_id":"67e05420d4dd3492097aeb77f44f7867","position":15.0,"number":15,"votes":0,"created_at":"2010/11/04 16:56:50 -0700","comments":1,"body":"The API seems to work when I do curl. But it breaks via python-github2. \r\n\r\n    >>> gh.commits.list(\"mojombo/grit\", \"master\")\r\n    Traceback (most recent call last):\r\n      File \"<console>\", line 1, in <module>\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/src/python-github2/github2/commits.py\", line 31, in list\r\n        filter=\"commits\", datatype=Commit)\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/src/python-github2/github2/core.py\", line 60, in get_values\r\n        values = self.make_request(*args, **kwargs)\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/src/python-github2/github2/core.py\", line 43, in make_request\r\n        response = self.request.get(self.domain, command, *args)\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/src/python-github2/github2/request.py\", line 53, in get\r\n        return self.make_request(\"/\".join(path_components))\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/src/python-github2/github2/request.py\", line 63, in make_request\r\n        return self.raw_request(url, extra_post_data, method=method)\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/src/python-github2/github2/request.py\", line 91, in raw_request\r\n        json = simplejson.loads(response_text)\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/lib/python2.6/site-packages/simplejson/__init__.py\", line 384, in loads\r\n        return _default_decoder.decode(s)\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/lib/python2.6/site-packages/simplejson/decoder.py\", line 402, in decode\r\n        obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n      File \"/Users/pydanny/projects/djangopackages/envdp/lib/python2.6/site-packages/simplejson/decoder.py\", line 420, in raw_decode\r\n        raise JSONDecodeError(\"No JSON object could be decoded\", s, idx)\r\n    JSONDecodeError: No JSON object could be decoded: line 1 column 0 (char 0)","title":"commits API is broken","updated_at":"2010/11/04 17:27:00 -0700","closed_at":"2010/11/04 17:27:00 -0700","html_url":"https://github.com/ask/python-github2/issues/15","user":"pydanny","labels":[],"state":"closed"},{"gravatar_id":"e40de1eb6e8a74cb96b3f07f3994f155","position":14.0,"number":14,"votes":0,"created_at":"2010/11/02 13:17:42 -0700","comments":2,"body":"Hi, \r\n\r\nJust a couple of small commits to fix minor problems I've found, and add support for some missing issues features.  If you prefer to receive changes in a different way, please just say and I'll rework these(and any future ones) to fit.\r\n\r\nI'll take this opportunity to say thanks for releasing this package, I've found it very useful when playing with the github API.\r\n\r\nThanks,\r\n\r\nJames.\r\n","title":"Small fixes and more support for issues","updated_at":"2010/12/09 22:41:52 -0800","diff_url":"https://github.com/ask/python-github2/pull/14.diff","patch_url":"https://github.com/ask/python-github2/pull/14.patch","pull_request_url":"https://github.com/ask/python-github2/pull/14","closed_at":"2010/12/10 06:32:31 -0800","html_url":"https://github.com/ask/python-github2/issues/14","user":"JNRowe","labels":[],"state":"closed"},{"gravatar_id":"b4f902096ea2ccfce71443d1d8fee5b3","position":13.0,"number":13,"votes":0,"created_at":"2010/10/20 09:38:43 -0700","comments":0,"body":"I added some more fields that are in the API but not on github2 Repositories:\r\n\r\n- created_at\r\n- pushed_at\r\n- has_wiki\r\n- has_issues\r\n- has_downloads","title":"More information on Repository","updated_at":"2010/10/29 03:23:50 -0700","diff_url":"https://github.com/ask/python-github2/pull/13.diff","patch_url":"https://github.com/ask/python-github2/pull/13.patch","pull_request_url":"https://github.com/ask/python-github2/pull/13","closed_at":"2010/10/29 03:23:50 -0700","html_url":"https://github.com/ask/python-github2/issues/13","user":"ojii","labels":[],"state":"closed"},{"gravatar_id":"4053d6caab18829c4e8d393b6afa8ad8","position":12.0,"number":12,"votes":0,"created_at":"2010/10/15 15:45:16 -0700","comments":1,"body":".. this directory is also used by the `pastedeploy` package\r\nhttp://twitter.com/ActiveState/status/27484677815\r\nPut it in site-packages/github2/tests instead.\r\n\r\n    ~/Library/Python/2.7/bin \r\n    ~/Library/Python/2.7/bin/github_manage_collaborators \r\n    ~/Library/Python/2.7/lib \r\n    ~/Library/Python/2.7/lib/python \r\n    ~/Library/Python/2.7/lib/python/site-packages \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2 \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2-0.1.3-py2.7.egg-info \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2-0.1.3-py2.7.egg-info/PKG-INFO \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2-0.1.3-py2.7.egg-info/SOURCES.txt \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2-0.1.3-py2.7.egg-info/dependency_links.txt \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2-0.1.3-py2.7.egg-info/top_level.txt \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2/__init__.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2/client.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2/commits.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2/core.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2/issues.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2/repositories.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2/request.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/github2/users.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/tests \r\n    ~/Library/Python/2.7/lib/python/site-packages/tests/__init__.py \r\n    ~/Library/Python/2.7/lib/python/site-packages/tests/unit.py ","title":"Avoiding polluting site-packages/tests/ directory","updated_at":"2010/12/09 22:39:34 -0800","closed_at":"2010/12/09 22:39:34 -0800","html_url":"https://github.com/ask/python-github2/issues/12","user":"srid","labels":[],"state":"closed"},{"gravatar_id":"9bfcdf9a72021d081a4cebf69a49ada8","position":11.0,"number":11,"votes":0,"created_at":"2010/10/15 04:42:12 -0700","comments":1,"body":"Python's timedelta did not have a 'total_seconds' method before python 2.7. This patches calculates seconds as documented at http://docs.python.org/library/datetime.html#datetime.timedelta.total_seconds.\n\nThis makes github2 compatible with python2.6 at least.\n\nPatch here: http://gist.github.com/628061","title":"Incompatibility for python 2.6: timedelta total_seconds","updated_at":"2011/04/13 13:06:54 -0700","closed_at":"2011/04/13 13:06:54 -0700","html_url":"https://github.com/ask/python-github2/issues/11","user":"arthur-debert","labels":[],"state":"closed"},{"gravatar_id":"f3794e603ef53b0513ab45b6565ee457","position":10.0,"number":10,"votes":0,"created_at":"2010/09/20 21:32:49 -0700","comments":1,"body":"I added a param to the Github class which enforces rate limits by sleeping the thread if requests are occurring too fast.\r\n\r\nIt's backwards compatible because delays only happen if requests_per_second is passed in.  Includes a test, some docstrings, and an updated README.\r\n","title":"Api limits","updated_at":"2010/09/20 22:55:16 -0700","diff_url":"https://github.com/ask/python-github2/pull/10.diff","patch_url":"https://github.com/ask/python-github2/pull/10.patch","pull_request_url":"https://github.com/ask/python-github2/pull/10","closed_at":"2010/09/21 05:55:06 -0700","html_url":"https://github.com/ask/python-github2/issues/10","user":"jdunck","labels":[],"state":"closed"},{"gravatar_id":"5b45540ae377ec54a071f313b7193a27","position":9.0,"number":9,"votes":0,"created_at":"2010/07/28 12:56:51 -0700","comments":2,"body":"    Traceback (most recent call last):\r\n      File \"migrate_to_github.py\", line 74, in <module>\r\n        gh = Github()\r\n    TypeError: __init__() takes at least 3 arguments (1 given)\r\n","title":"Doesn't support unauthenticated session","updated_at":"2011/04/18 07:04:50 -0700","closed_at":"2011/04/18 07:04:50 -0700","html_url":"https://github.com/ask/python-github2/issues/9","user":"dabrahams","labels":[],"state":"closed"},{"gravatar_id":"71c4e8223f5bddfbcce0607d387d2125","position":8.0,"number":8,"votes":1,"created_at":"2010/06/20 06:13:37 -0700","comments":1,"body":"There is a cool new way to do Github authentication: http://github.com/blog/656-github-oauth2-support","title":"support for the new OAuth2 authentication","updated_at":"2011/04/26 06:31:50 -0700","closed_at":"2011/04/26 06:31:50 -0700","html_url":"https://github.com/ask/python-github2/issues/8","user":"tarpas","labels":[],"state":"closed"},{"gravatar_id":"7ea0cc75793eb2b1ada4abc953a41592","position":7.0,"number":7,"votes":0,"created_at":"2010/05/26 17:08:41 -0700","comments":3,"body":"Python 2.6 includes simplejson (renaming to just json), removing the need for the external dep. To work on 2.5 and 2.6, use try:import:\r\nhttp://github.com/adamv/python-github2/commit/5b2f09d89420aac0d071522b3fbed9b026af6def\r\n","title":"Use json instead of simplejson on Python 2.6","updated_at":"2011/04/09 10:46:22 -0700","closed_at":"2011/04/09 10:46:22 -0700","html_url":"https://github.com/ask/python-github2/issues/7","user":"adamv","labels":[],"state":"closed"},{"gravatar_id":"7ea0cc75793eb2b1ada4abc953a41592","position":6.0,"number":6,"votes":0,"created_at":"2010/05/25 21:59:37 -0700","comments":2,"body":"An object's __repr__ in Python 2.x is required to be ASCII. Various objects in this API return unicode values, as unicode is returned from titles, etc. from the web calls, and those are used in __repr__.\r\n\r\nIn my particular case, I got an error printing Issues that happened to contain non-ASCII characters.\r\n\r\nI'll probably add a commit to this bug tomorrow/later.","title":"__repr__ should return ASCII on Python 2.x","updated_at":"2010/12/08 19:46:28 -0800","closed_at":"2010/12/08 19:46:28 -0800","html_url":"https://github.com/ask/python-github2/issues/6","user":"adamv","labels":[],"state":"closed"},{"gravatar_id":"2e47ce8a038f8eaf3fe80c069e380814","position":4.0,"number":4,"votes":0,"created_at":"2010/04/17 17:24:29 -0700","comments":1,"body":"This package isn't on PyPi near as I can tell.\r\n\r\n* http://pypi.python.org/pypi/github2 \r\n* http://pypi.python.org/pypi/python-github2\r\n\r\nResponse from easy_install:\r\nNo local packages or download links found for python-github2","title":"Not installable via easy_install","updated_at":"2010/04/19 02:26:01 -0700","closed_at":"2010/04/19 02:26:01 -0700","html_url":"https://github.com/ask/python-github2/issues/4","user":"joestump","labels":[],"state":"closed"},{"gravatar_id":"d819f7576d53088db65789b9732141b3","position":3.0,"number":3,"votes":0,"created_at":"2009/11/12 21:16:20 -0800","comments":2,"body":"In your README, your import path says\r\n\r\n     >>> from github.client import Github\r\n\r\nbut it should really be\r\n\r\n     >>> from github2.client import Github","title":"README has improper imports","updated_at":"2009/11/13 03:32:29 -0800","closed_at":"2009/11/13 03:32:29 -0800","html_url":"https://github.com/ask/python-github2/issues/3","user":"justinlilly","labels":[],"state":"closed"},{"gravatar_id":"d819f7576d53088db65789b9732141b3","position":2.0,"number":2,"votes":0,"created_at":"2009/11/12 21:15:17 -0800","comments":1,"body":"When searching repos for django, I get an error caused by the emdash in the description of http://github.com/brosner/django \r\n\r\n    Traceback: \r\n    >>> github.repos.search('django')\r\n    Traceback (most recent call last):\r\n      File \"<stdin>\", line 1, in <module>\r\n      File \"/Users/jlilly/src/githubgraphs/env/lib/python2.5/site-packages/github2/repositories.py\", line 21, in search\r\n        return self.make_request(\"search\", query, filter=\"repositories\")\r\n      File \"/Users/jlilly/src/githubgraphs/env/lib/python2.5/site-packages/github2/core.py\", line 42, in make_request\r\n        response = self.request.get(self.domain, command, *args)\r\n      File \"/Users/jlilly/src/githubgraphs/env/lib/python2.5/site-packages/github2/request.py\", line 46, in get\r\n        return self.make_request(\"/\".join(path_components))\r\n      File \"/Users/jlilly/src/githubgraphs/env/lib/python2.5/site-packages/github2/request.py\", line 55, in make_request\r\n        return self.raw_request(url, extra_post_data)\r\n      File \"/Users/jlilly/src/githubgraphs/env/lib/python2.5/site-packages/github2/request.py\", line 71, in raw_request\r\n        response_text = response.read().encode(\"utf-8\")\r\n    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7065: ordinal not in range(128)\r\n","title":"Unicode handling error","updated_at":"2009/11/13 03:32:29 -0800","closed_at":"2009/11/13 03:32:29 -0800","html_url":"https://github.com/ask/python-github2/issues/2","user":"justinlilly","labels":[],"state":"closed"},{"gravatar_id":"7e8b501f7f579c66ddac7e65cb7962b4","position":1.0,"number":1,"votes":0,"created_at":"2009/04/18 13:04:09 -0700","comments":1,"body":"This to support getting raw blob/tree data as specified in http://develop.github.com/p/object.html.","title":"option to make_request so it doesn't parse the response as json.","updated_at":"2011/06/20 09:37:30 -0700","closed_at":"2011/06/20 09:37:30 -0700","html_url":"https://github.com/ask/python-github2/issues/1","user":"ask","labels":[],"state":"closed"}]}